// Package util contains helpers
package util // import "github.com/dyweb/gommon/util"

func GeneratedHeader(generator string, template string) string {
	return "// Code generated by " + generator + " from " + template + " DO NOT EDIT.\n"
}
