package noodle

import (
	"fmt"
	"github.com/dyweb/gommon/util/fsutil"
	"os"
	"testing"
)

func TestGenerateEmbed(t *testing.T) {
	t.Skip("modification time result in different binary data")

	b, err := GenerateEmbed("_examples/embed/assets")
	if err != nil {
		t.Fatal(err)
	}
	b = append([]byte("//Code generated by gommon from config/gommon.yml DO NOT EDIT.\npackage gen\n"), b...)
	fsutil.WriteFile("_examples/embed/gen/noodle.go", b)
}

func TestFileMode(t *testing.T) {
	// 2147483648
	fmt.Printf("%#o", os.ModeDir)
}
