package noodle

import (
	"fmt"
	"github.com/dyweb/gommon/util/fsutil"
	"os"
	"testing"
)

func TestGenerateEmbed(t *testing.T) {
	b, err := GenerateEmbed("_examples/embed/assets")
	if err != nil {
		t.Fatal(err)
	}
	b = append([]byte("//Code generated by gommon from config/gommon.yml DO NOT EDIT.\npackage main\n"), b...)
	fsutil.WriteFile("_examples/embed/t.go", b)
}

func TestFileMode(t *testing.T) {
	// 2147483648
	fmt.Printf("%#0d", os.ModeDir)
}
