// Code generated by gommon from util/color/color_generated.go.tmpl DO NOT EDIT.
package color

const (
	GreenCode = 32

	PurpleCode = 35

	RedCode = 31

	YellowCode = 33

	BlueCode = 34

	CyanCode = 36

	GrayCode = 37
)

const (
	YellowStart = "\x1b[33m"

	BlueStart = "\x1b[34m"

	CyanStart = "\x1b[36m"

	GrayStart = "\x1b[37m"

	GreenStart = "\x1b[32m"

	PurpleStart = "\x1b[35m"

	RedStart = "\x1b[31m"

	End = "\x1b[0m"
)

func Purple(str string) string {
	return "\x1b[35m" + str + "\x1b[0m"
}

func Red(str string) string {
	return "\x1b[31m" + str + "\x1b[0m"
}

func Yellow(str string) string {
	return "\x1b[33m" + str + "\x1b[0m"
}

func Blue(str string) string {
	return "\x1b[34m" + str + "\x1b[0m"
}

func Cyan(str string) string {
	return "\x1b[36m" + str + "\x1b[0m"
}

func Gray(str string) string {
	return "\x1b[37m" + str + "\x1b[0m"
}

func Green(str string) string {
	return "\x1b[32m" + str + "\x1b[0m"
}
