// +build ignore

// Code generated by gommon from config/gommon.yml DO NOT EDIT.

package config

import dlog "github.com/dyweb/gommon/log"

func (c *YAMLConfig) SetLogger(logger *dlog.Logger) {
	c.log = logger
}

func (c *YAMLConfig) GetLogger() *dlog.Logger {
	return c.log
}

func (c *YAMLConfig) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
